version: '2'

services:
#  mysql:
#    container_name: mysql
#    image: mysql:5.5
#    environment:
#      - MYSQL_DATABASE=fatturini_dev
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=root
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./db-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: score-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb-data:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  # web:
  #   container_name: score-web
  #   tty: true # Enables debugging capabilities when attached to this container.
  #   # image: 'bitnami/node:9'
  #   image: 'node:lts-alpine'
  #   # command: bash -c "yarn && yarn dev"
  #   command: "sh -c 'yarn && yarn dev'"
  #   environment:
  #     - HOST=localhost
  #     - PORT=8000
  #     - NODE_ENV=development
  #     - SKIP_DB_WAIT=0
  #     - SKIP_DB_MIGRATION=0
  #     - SKIP_NPM_INSTALL=0
  #     - SKIP_BOWER_INSTALL=0
  #     - offline=false
  #     - MONGO_URL=mongodb://mongodb:27017
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app

  web:
    container_name: score-web
    tty: true # Enables debugging capabilities when attached to this container.
    restart: always
    build: .
    environment:
      - HOST=localhost
      - PORT=8000
      - NODE_ENV=development
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
      - offline=false
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - 8000:8000
